name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      # This uses a tool called mkdocs (https://www.mkdocs.org/)
      # to publish the GitHub Pages site. I like mkdocs because
      # it is just markdown and very, very little other templating
      # required.
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          CONFIG_FILE: mkdocs.yml
          EXTRA_PACKAGES: libffi libffi-dev py3-pip py3-pillow py3-cffi py3-brotli gcc g++ musl-dev python3-dev pango zlib zlib-dev weasyprint
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REQUIREMENTS: requirements.txt